name: test
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Golang
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.1'
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic -args "${{ secrets.TEST_USER }}" "${{ secrets.TEST_PASS }}"
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt